### ISSUE TITLE
Socket errors after laptop sleeps

### ISSUE THREAD

**Issue by eyeseast** [tarbell-project/tarbell#322]
I get this error pretty much every time I close my laptop with the dev server running:

```python
Traceback (most recent call last):
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/chris_amico/code/project/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/chris_amico/code/project/src/tarbell/tarbell/app.py", line 527, in preview
    raise e
error: [Errno 49] Can't assign requested address
```

It's an easy fix -- just restart the server, or save `tarbell_config.py` (which restarts the server) -- but it's annoying.

**Comment by eads** [comment]
Yeaaah, I still haven't figured out how to properly catch this. If you have
any ideas...

The fact the Werkzeug spawns a child process seems to be part of the issue.

**Comment by eyeseast** [comment]
Ugh. Werkzeug. 

I almost wonder if we can just trigger a server reload when this error comes up, or somehow kill and reload the child process.
