### ISSUE TITLE
`HttpAccessTokenRefreshError: invalid_grant` exception when running `tarbell serve`

### ISSUE THREAD

**Issue by ghing** [tarbell-project/tarbell#437]
Two of our team members had this issue yesterday.  

When running `tarbell serve` in a previously-created project, tarbell raises a `HttpAccessTokenRefreshError: invalid_grant` exception.

Here's the traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 529, in preview
    context = self.get_context(publish)
  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 605, in get_context
    context.update(self.get_context_from_gdoc())
  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 666, in get_context_from_gdoc
    self.data = self._get_context_from_gdoc(self.project.SPREADSHEET_KEY)
  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 680, in _get_context_from_gdoc
    content = self.export_xlsx(key)
  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 695, in export_xlsx
    spreadsheet_file = self.client.files().get(fileId=key).execute()
  File "/usr/local/lib/python2.7/site-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/googleapiclient/http.py", line 716, in execute
    body=self.body, headers=self.headers)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 607, in new_request
    self._refresh(request_orig)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 854, in _refresh
    self._do_refresh_request(http_request)
  File "/usr/local/lib/python2.7/site-packages/oauth2client/client.py", line 907, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
HttpAccessTokenRefreshError: invalid_grant
```

**Comment by ghing** [comment]
I believe this is due to the OAuth token for the Drive API become stale somehow.  We were able to fix this issue by deleting the `tarbell` item in the `login` keychain via the Keychain Access program (we run Mac OS X).

![screen shot 2016-10-25 at 8 58 58 am](https://cloud.githubusercontent.com/assets/110420/19688940/49be0b10-9a91-11e6-8319-f37d38dc5f41.png)

After deleting that item and re-running `tarbell serve`, the users were prompted to re-authenticate to the Drive API in the same way that happens after you first set up Tarbell.

I could see a few ways to address this better:

* Catch the exception and delete the key and force re-authentication.  However, I'm not sure if there are other cases where this exception might be raised.
* Catch the exception and have a more human error message that tells people how they might fix it
* Document this error
